name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - name: Run linter
        run: yarn lint
      - name: Check formatting
        run: yarn prettier
      - name: Build
        run: yarn build
      - name: Run tests
        run: yarn test
      - name: Run end-to-end tests (headless)
        run: yarn e2e:headless
